# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L1BQIBkqMS2VkLYjOEMh_E9YHOPtbX9_
"""

import streamlit as st
import joblib, json, pandas as pd

PIPE = joblib.load("artefactos/v1/pipeline_NNM.joblib")
st.title("Predicción de Riesgo de Preeclampsia")

edad = st.number_input("Edad (años)", 15, 50, 30)
imc = st.number_input("IMC", 10.0, 50.0, 25.0)
pa_sis = st.number_input("Presión sistólica", 80, 200, 120)
pa_dia = st.number_input("Presión diastólica", 50, 130, 80)
hipertension = st.selectbox("Hipertensión previa", ["0", "1"])
diabetes = st.selectbox("Diabetes", ["0", "1"])
creatinina = st.number_input("Creatinina", 0.1, 2.0, 1.0)
ant_fam = st.selectbox("Antecedente familiar de HTA", ["0", "1"])
tec_repro = st.selectbox("Técnica de reproducción asistida", ["0", "1"])

if st.button("Predecir"):
    df = pd.DataFrame([{
        "edad": edad, "imc": imc, "p_a_sistolica": pa_sis, "p_a_diastolica": pa_dia,
        "hipertension": hipertension, "diabetes": diabetes, "creatinina": creatinina,
        "ant_fam_hiper": ant_fam, "tec_repro_asistida": tec_repro
    }])
    proba = PIPE.predict_proba(df)[0,1]
    label = "RIESGO" if proba >= 0.5 else "SIN RIESGO"
    st.success(f"Probabilidad de riesgo: {proba*100:.2f}% → {label}")